support startpage and duckduckgo
wong2/chat-gpt-google-extension pull request #21
Opened 2022-12-05 08:00 UTC by ttttmr

#20

2022-12-05 08:12 UTC, aboutmydreams commented
cool, i think it's very valuable

2022-12-05 19:43 UTC, 1zizi1 requested changes

2022-12-05 19:43 UTC, 1zizi1 commented on src/content-script/index.mjs
> +  }
Maybe refactor this into a function so that other search engines can be cleanly added

2022-12-05 22:41 UTC, Julian88Tex commented
Partial duplicate of #8

2022-12-09 08:14 UTC, wong2 commented
https://github.com/wong2/chat-gpt-google-extension/pull/31

2022-12-09 08:14 UTC, closed without merging